# Generated by Django 4.0.3 on 2022-03-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queries',
            name='format',
            field=models.PositiveIntegerField(choices=[(0, 'MicrosoftOffice (.docx)'), (1, 'LibreOffice (.odt)')], default=0, verbose_name='Выберите формат документа'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='url',
            field=models.CharField(max_length=3000, verbose_name='Введите ссылку на документ'),
        ),
    ]
